apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "database.marklogic.com/v1alpha1",
          "kind": "MarklogicCluster",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "marklogic-operator-kubernetes",
              "app.kubernetes.io/instance": "marklogiccluster-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "marklogiccluster",
              "app.kubernetes.io/part-of": "marklogic-operator-kubernetes"
            },
            "name": "marklogiccluster-sample"
          },
          "spec": {
            "markLogicGroups": [
              {
                "isBootstrap": true,
                "spec": {
                  "image": "marklogicdb/marklogic-db:11.1.0-centos-1.1.1",
                  "name": "dnode",
                  "replicas": 2
                }
              },
              {
                "isBootstrap": false,
                "spec": {
                  "image": "marklogicdb/marklogic-db:11.1.0-centos-1.1.1",
                  "name": "enode",
                  "replicas": 1
                }
              }
            ]
          }
        },
        {
          "apiVersion": "database.marklogic.com/v1alpha1",
          "kind": "MarklogicGroup",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "marklogic-operator-kubernetes",
              "app.kubernetes.io/instance": "marklogicgroup-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "marklogicgroup",
              "app.kubernetes.io/part-of": "marklogic-operator-kubernetes"
            },
            "name": "marklogicgroup-sample"
          },
          "spec": {
            "auth": {
              "adminPassword": "pass",
              "adminUsername": "user"
            },
            "groupConfig": {
              "name": "node"
            },
            "image": "marklogicdb/marklogic-db:11.1.0-centos-1.1.2",
            "name": "marklogic",
            "replicas": 2,
            "terminationGracePeriodSeconds": 9,
            "updateStrategy": "OnDelete"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-06-21T06:42:12Z"
    operators.operatorframework.io/builder: operator-sdk-v1.34.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: marklogic-operator-kubernetes.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MarklogicCluster is the Schema for the marklogicclusters API
      displayName: Marklogic Cluster
      kind: MarklogicCluster
      name: marklogicclusters.database.marklogic.com
      version: v1alpha1
    - description: MarklogicGroup is the Schema for the marklogicgroup API
      displayName: Marklogic Group
      kind: MarklogicGroup
      name: marklogicgroups.database.marklogic.com
      version: v1alpha1
  description: Operator for managing marklogic server
  displayName: marklogic-operator-kubernetes
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - daemonsets
          - deployments
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          - pods
          - secrets
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - database.marklogic.com
          resources:
          - marklogicclusters
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - database.marklogic.com
          resources:
          - marklogicclusters/finalizers
          verbs:
          - update
        - apiGroups:
          - database.marklogic.com
          resources:
          - marklogicclusters/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - database.marklogic.com
          resources:
          - marklogicgroups
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - database.marklogic.com
          resources:
          - marklogicgroups/finalizers
          verbs:
          - update
        - apiGroups:
          - database.marklogic.com
          resources:
          - marklogicgroups/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: marklogic-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: marklogic-operator-kubernetes
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: marklogic-operator-kubernetes
          control-plane: controller-manager
        name: marklogic-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: progressofficial/marklogic-operator-kubernetes:1.0.0
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: marklogic-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: marklogic-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - marklogic
  - datbase
  links:
  - name: Marklogic Kubernetes Operator
    url: https://marklogic-operator-kubernetes.domain
  maturity: alpha
  provider:
    name: Progress Software Corp
    url: https://www.progress.com/
  version: 0.0.1
