# permissions for end users to view marklogicgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: marklogicgroup-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubernetes-poc-artifacts
    app.kubernetes.io/part-of: kubernetes-poc-artifacts
    app.kubernetes.io/managed-by: kustomize
  name: marklogicgroup-viewer-role
rules:
- apiGroups:
  - operator.marklogic.com
  resources:
  - marklogicgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.marklogic.com
  resources:
  - marklogicgroups/status
  verbs:
  - get
