# permissions for end users to edit marklogicclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: marklogiccluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: marklogic-kubernetes-operator
    app.kubernetes.io/part-of: marklogic-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: marklogiccluster-editor-role
rules:
- apiGroups:
  - database.marklogic.com
  resources:
  - marklogicclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.marklogic.com
  resources:
  - marklogicclusters/status
  verbs:
  - get
