apiVersion: database.marklogic.com/v1alpha1
kind: MarklogicGroup
metadata:
  labels:
    app.kubernetes.io/name: marklogicgroup
    app.kubernetes.io/instance: marklogicgroup-sample
    app.kubernetes.io/part-of: marklogic-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: marklogic-kubernetes-operator
  name: marklogicgroup-sample
spec:
  # TODO(user): Add fields here
