apiVersion: database.marklogic.com/v1alpha1
kind: MarklogicCluster
metadata:
  labels:
    app.kubernetes.io/name: marklogiccluster
    app.kubernetes.io/instance: marklogiccluster-sample
    app.kubernetes.io/part-of: marklogic-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: marklogic-kubernetes-operator
  name: marklogiccluster-sample
spec:
  # TODO(user): Add fields here
