apiVersion: marklogic.progress.com/v1
kind: MarklogicCluster
metadata:
  name: ml-dynamic-host
  namespace: ml-dynamic-host
spec:
  image: "progressofficial/marklogic-db:12.0.3-ubi9-rootless-2.2.6"
  markLogicGroups:
  - name: bootstrap
    isBootstrap: true
    replicas: 1
    groupConfig:
      name: bootstrap
  - name: dynamic
    isDynamic: true
    dynamic:
      tokenDuration: PT15M
    replicas: 1
    groupConfig:
      name: dynamic
