apiVersion: database.marklogic.com/v1alpha1
kind: MarklogicCluster
metadata:
  labels:
    app.kubernetes.io/name: marklogiccluster
    app.kubernetes.io/instance: marklogiccluster-sample
    app.kubernetes.io/part-of: marklogic-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: marklogic-kubernetes-operator
  name: marklogiccluster-sample
spec:
  image: "progressofficial/marklogic-db:11.3.0-ubi-rootless"
  auth:
    adminUsername: user
    adminPassword: pass
# This is the cluster level configuration that will apply to all the groups
  # storage:
  #   size: 5Gi
  haproxy: 
    enabled: true
    appServers:
      - name: "admin"
        port: 8001
      - name: "app-service"
        port: 8000
    stats:
      enabled: true
      port: 1024
  resources:
    requests:
      memory: "4Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "1"
  # logCollection:
  #   enabled: true
  #   image: fluent/fluent-bit:3.1.1
  #   files:
  #     errorLogs: true
  #     accessLogs: true
  #     requestLogs: true
  #     crashLogs: true
  #     auditLogs: true
  #   outputs: |-
  #       [OUTPUT]
  #         name loki
  #         match *
  #         host loki.loki.svc.cluster.local
  #         port 3100
  #         labels job=fluent-bit
  #         http_user admin
  #         http_passwd admin
  markLogicGroups:
  - replicas: 1
    name: dnode
    # storage:
    #   size: 10Gi
    resources:
      requests:
        memory: "5Gi"
        cpu: "1"
      limits:
        memory: "5Gi"
        cpu: "1"
    isBootstrap: true
  - replicas: 2
    name: enode
    isBootstrap: false