apiVersion: database.marklogic.com/v1alpha1
kind: MarklogicCluster
metadata:
  labels:
    app.kubernetes.io/name: marklogiccluster
    app.kubernetes.io/instance: marklogiccluster-sample
    app.kubernetes.io/part-of: marklogic-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: marklogic-kubernetes-operator
  name: ml-cluster
spec:
  image: "progressofficial/marklogic-db:11.3.0-ubi-rootless"
  auth:
    adminUsername: user
    adminPassword: pass
# This is the cluster level configuration that will apply to all the groups
  # storage:
  #   size: 5Gi

  ## Configuration for the HAProxy load balancer
  ## An out of box load balancer with configured to handle cookie based session affinity that required by most MarkLogic applications.
  ## It also support multi-statement transaction and ODBC connections.  
  ## Uncomment the following lines to enable HAProxy configuration
  haproxy: 
    enabled: false
    # pathBasedRouting: true
    # frontendPort: 8080
    # tcpPorts:
    #   enabled: true
    #   ports:
    #     - name: odbc
    #       type: TCP
    #       port: 5432
    # appServers:
    #   - name: "app-service"
    #     port: 8000
    #     path: "/console"
    #   - name: "admin"
    #     port: 8001
    #     path: "/adminUI"
    #   - name: "manage"
    #     port: 8002
    #     path: "/manage"
    # stats:
    #   enabled: true
    #   port: 1024
  # resources:
  #   requests:
  #     memory: "4Gi"
  #     cpu: "1"
  #   limits:
  #     memory: "4Gi"
  #     cpu: "1"
    ## Configure Ingress
    ## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
    # ingress: 
    #   enabled: true
    #   ingressClassName: "alb"

    #   ## Ingress labels
    #   ## ref: https://kubernetes.io/docs/concepts/overvsiew/working-with-objects/labels/
    #   labels:
    #     app.kubernetes.io/name: marklogiccluster
    #     app.kubernetes.io/instance: marklogiccluster-sample
    
    #   ## Ingress annotations
    #   ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
    #   annotations: 
    #     alb.ingress.kubernetes.io/healthcheck-port: '80'
    #     alb.ingress.kubernetes.io/healthcheck-path: /adminUI
    #     alb.ingress.kubernetes.io/success-codes: '200-401'
    #     alb.ingress.kubernetes.io/load-balancer-name: mlingress
    #     alb.ingress.kubernetes.io/scheme: internet-facing
    #     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    #     alb.ingress.kubernetes.io/target-group-attributes: load_balancing.algorithm.type=least_outstanding_requests
    #     # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:XXXXXXXXXXX:certificate/XxXXXXXX-xxxx-XXXX-XXXX-XXXXXXXxxxxXXX
    #     alb.ingress.kubernetes.io/target-type: ip
    #     alb.ingress.kubernetes.io/group.name: mlingress-group
    #     alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=600,routing.http.xff_header_processing.mode=append

      ## Ingress hosts
      ## add default hosts and additional hosts
      ## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-rules
      # host: ""
      # additionalHosts: []
    
      ## Ingress TLS
      ## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
      # tls: {}
          # - secretName: your-certificate-name
          #   hosts:
          #     - marklogic.example.com
  
  # logCollection:
  #   enabled: true
  #   image: fluent/fluent-bit:3.1.1
  #   files:
  #     errorLogs: true
  #     accessLogs: true
  #     requestLogs: true
  #     crashLogs: true
  #     auditLogs: true
  #   outputs: |-
  #       [OUTPUT]
  #         name loki
  #         match *
  #         host loki.loki.svc.cluster.local
  #         port 3100
  #         labels job=fluent-bit
  #         http_user admin
  #         http_passwd admin

  ## To configure networkPolicy, set enabled: true and uncomment the following lines 
  ## Below is an example of networkPolicy, update it as per your requirements
  ## ref: https://kubernetes.io/docs/concepts/services-networking/network-policies
  # networkPolicy:
  #   enabled: true
  #   policyTypes:
  #     - Ingress
  #     - Egress
  #   podSelector: {}
  #   ingress:
  #     - from:
  #         - podSelector:
  #             matchLabels:
  #               app.kubernetes.io/name: marklogic
  #               app.kubernetes.io/instance: marklogic
  #       ports:
  #         - protocol: TCP
  #           port: 8000
  #   egress:
  #     - to:
  #         - podSelector:
  #             matchLabels:
  #               app.kubernetes.io/name: marklogic
  #               app.kubernetes.io/instance: marklogicgroup
  #       ports:
  #         - protocol: TCP
  #           port: 8000
  tls:
    enableOnDefaultAppServers: false
  markLogicGroups:
  - replicas: 1
    name: dnode
    groupConfig:
      name: dnode
      enableXdqpSsl: true
    # storage:
    #   size: 10Gi
    # resources:
    #   requests:
    #     memory: "5Gi"
    #     cpu: "1"
    #   limits:
    #     memory: "5Gi"
    #     cpu: "1"
    isBootstrap: true
  - replicas: 1
    name: enode
    groupConfig:
      name: enode
      enableXdqpSsl: true
    isBootstrap: false
