apiVersion: database.marklogic.com/v1alpha1
kind: MarklogicCluster
metadata:
  labels:
    app.kubernetes.io/name: marklogiccluster
    app.kubernetes.io/instance: marklogiccluster-sample
    app.kubernetes.io/part-of: marklogic-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: marklogic-kubernetes-operator
  name: single-node
  namespace: dev-env
spec:
  image: "progressofficial/marklogic-db:11.3.0-ubi-rootless"
  ## It is recommended to use Kubernetes secrets to store the admin credentials
  ## If you do not provide the secret with admin credentials, the operator will generate a secret for you containing admin credentials
  # auth:
  #   secretName: marklogic-admin-secret
  #   adminUsername: admin
  #   adminPassword: admin
  markLogicGroups:
  - replicas: 1
    name: node
    groupConfig:
      name: node
      enableXdqpSsl: true
    storage:
      size: 10Gi
    resources:
      requests:
        memory: "4Gi"
        cpu: 2000m
      limits:
        memory: "4Gi"
        cpu: 2000m
    isBootstrap: true

  