apiVersion: v1
kind: Service
metadata:
  name: marklogic-operator-controller-manager-metrics-service
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: marklogic-operator-kubernetes
    app.kubernetes.io/part-of: marklogic-operator-kubernetes
    control-plane: controller-manager
  {{- include "marklogic-operator-kubernetes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
    {{- include "marklogic-operator-kubernetes.selectorLabels" . | nindent 4 }}
  ports:
  {{- if .Values.metrics.secure }}
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  {{- else }}
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  {{- end }}
